name: Update Bin Calendar

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight
  workflow_dispatch: # Allows you to trigger it manually

permissions:
  contents: write # Essential for the bot to save the bins.ics file

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install uk_bin_collection selenium

      - name: Run bin scraper
        run: |
          # The tool is now run as a package directly
          python3 -m uk_bin_collection.uk_bin_collection EastDunbartonshireCouncil "https://www.eastdunbarton.gov.uk/services/a-z-of-services/bins-waste-and-recycling/bins-and-recycling/collections/?uprn=132020540&m=CfDJ8NH03gsfdeVFlP61mROFUWd8FCFwfatyzh3TGarEg5KiJlVT5WYMBNh79GvydN8UaJTvs7Fp-qSOgBdkD8tq__iLes7ad0kP9wQtbpShz7GWSjmYi5oJSZVZaDBMBmucZ6XnhYahkVZ1z6tbe8eg0GE" -o bins.ics

      - name: Commit and push changes
        run: |
          git config --global user.name 'BinBot'
          git config --global user.email 'bot@github.com'
          git add bins.ics
          git commit -m "Update bin dates" || exit 0
          git push
